# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-18 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edurep', '0004_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='edurepsource',
            name='collection_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
