# Generated by Django 2.2.10 on 2020-02-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edurep', '0007_datascope_v0-16'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edurepharvest',
            old_name='completed_at',
            new_name='harvested_at',
        ),
    ]
