# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-09 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol_harvester', '0008_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
