# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pol_harvester', '0010_wikipedia_corpera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrangement',
            options={'get_latest_by': 'id', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'id', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'get_latest_by': 'id', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'get_latest_by': 'id', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='freeze',
            options={'get_latest_by': 'id', 'ordering': ['id']},
        ),
    ]
