# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-02 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol_harvester', '0013_alpha_to_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaldiaspireresource',
            name='runtime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaldinlresource',
            name='runtime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
