# Generated by Django 2.2.10 on 2020-02-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol_harvester', '0014_datascope_v0-16'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
