# Generated by Django 2.2.10 on 2020-04-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pol_harvester', '0015_improved_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeze',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
