# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_query_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryranking',
            name='slug',
            field=models.SlugField(default='slug', max_length=255),
            preserve_default=False,
        ),
    ]
