# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-13 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alpha_to_beta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletext',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
