# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncartridge',
            name='manifest',
            field=models.TextField(blank=True),
        ),
    ]
