# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_commoncartridge_manifest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncartridge',
            name='file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
